// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOgxWO8tjscVwWwQ_RJQ_KC8mnNZfAHcY',
    appId: '1:204903741145:android:f2a47489aa950c6772f0c8',
    messagingSenderId: '204903741145',
    projectId: 'design-project-be175',
    storageBucket: 'design-project-be175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa_zEMcl__I-3pIGE9rQmkHffOydYswl4',
    appId: '1:204903741145:ios:0cf447f2cd5e840d72f0c8',
    messagingSenderId: '204903741145',
    projectId: 'design-project-be175',
    storageBucket: 'design-project-be175.appspot.com',
    androidClientId: '204903741145-97qtlcsgqgq57f944fr62opj003fqe5f.apps.googleusercontent.com',
    iosClientId: '204903741145-ah76v5n327o4qd5q90lp21k51rp78k1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.designProject',
  );
}
